[workspace]
authors = ["rashid <muhammad.rashid@unito.it>"]
name = "advis"
version = "0.1.0"
platforms = ["linux-64"]

# Keep conda-forge first for generic deps.
channels = [
  "nvidia",
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/robostack-jazzy",
  "pytorch"
]

[activation.env]
PYTHONPATH = "${PIXI_PROJECT_ROOT}/src:${PYTHONPATH}"
RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp"
CYCLONEDDS_URI = "/home/unito/dm/distrimuse-seds/cyclonedds.xml"
ROS_DOMAIN_ID="1"

[dependencies]
python = "3.12.*"
numpy = { version = "*", channel = "https://prefix.dev/conda-forge" }

mkl = { version = "*", channel = "https://prefix.dev/conda-forge" }

pytorch = { version = "*", channel = "pytorch" }
torchvision = { version = "*", channel = "pytorch" }
pytorch-cuda = { version = "12.1.*", channel = "pytorch" }

ros-jazzy-rclpy = "*"
ros-jazzy-sensor-msgs = "*"
ros-jazzy-cv-bridge = "*"
scipy = ">=1.17.1,<2"
matplotlib = ">=3.10.8,<4"
plotly = ">=6.6.0,<7"
scikit-image = ">=0.26.0,<0.27"
tqdm = ">=4.67.3,<5"
scikit-learn = ">=1.8.0,<2"
pandas = ">=3.0.2,<4"


ros-jazzy-rmw-cyclonedds-cpp = "*"

